### ISSUE TITLE
能否让开发者自己在YCDownloadItem中添加拓展字段？

### ISSUE THREAD

**Issue by hupfei** [onezens/YCDownloadSession#15]
毕竟YCDownloadItem中的字段有时候不满足开发者的需求，如何扩展？

**Comment by onezens** [comment]
YCDownloadItem 可以扩展字段，你可以自己在YCDownloadManager里面加个入口，我有时间了加个，然后提交上去

**Comment by hupfei** [comment]
自己直接修改你的代码当然可以解决，但是以后你代码更新了我这边不得改死

**Comment by onezens** [comment]
https://github.com/onezens/YCDownloadSession/blob/c16ff382f6feb64ee82f3d0896d5576ec45f8ba5/YCDownloadSession/YCDownloadSession/YCDownloadManager.h#L31
