### ISSUE TITLE
求指教

### ISSUE THREAD

**Issue by OCer** [onezens/YCDownloadSession#16]
我测试的时候发现了些问题，表示很不解：
1、APP在下载过程中突然崩溃了，如何去保存completionHandler()？

2、在- (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)(void))completionHandler 中，好像并不需要创建参照？ 我发现没创建也是OK的，不知道和创建了有什么区别

3、如果我创建了多个NSURLSession，到后台后是不是要保存多份completionHandler()？

4、我重新进入APP的时候，创建NSURLSession就自动给我继续下载了，导致我在逻辑处理出了问题，怎么让它不自动下载？

**Comment by onezens** [comment]
1. completionHandler 奔溃后没有必要保存， 因为是当前活跃app有效
2. 看我博客描述，看completionHandler 引用和不引用的区别
3. 每一个后台session有一个标识，根据标识保存和处理
4. 后台session奔溃重启默认会继续下载，如需不自动下载，启动后自己暂停就行（自行处理）

**Comment by onezens** [comment]
App 启动后暂停下载任务的逻辑，部分情况下是有问题

https://github.com/onezens/YCDownloadSession/blob/10e21fddcfa4114af26399adf58ed06ed6b82bf8/YCDownloadSession/YCDownloadSession/YCDownloadSession.m#L70

**Comment by OCer** [comment]
关键在于启动后我怎么去检测NSURLSession在下载呢？ 
我在创建NSURLSession的时候就给我下载了，连task都没创建 - -
我创建task是有一些逻辑的  不希望创建task才去暂停

**Comment by OCer** [comment]
```
NSURLSessionDownloadTask *task = nil;
    NSData *resumeData = [[self dataDic] objectForKey:identifier];
    if (resumeData)
    {
        kLog(@"断点续传");
        // 断点续传
        if ([Tools getSystemVersion] >= 10.0f) // 解决断点续传在iOS10以上的bug
        {
            task = [session downloadTaskWithCorrectResumeData:resumeData];
        }
        else
        {
            task = [session downloadTaskWithResumeData:resumeData];
        }
    }
    else
    {
        kLog(@"开启一个新的下载");
        // 启动一个下载任务
        task = [session downloadTaskWithRequest:request];
    }
    [[self taskList] addObject:task];

    // WIFI状态开始下载
    if ([[NetworkState shareNetworkState] state] == AFNetworkReachabilityStatusReachableViaWiFi)
    {
        kLog(@"WIFI状态开始下载");
        [task resume];
        [model setDownloadState:downloadStateLoading];
        [[NSNotificationCenter defaultCenter] postNotificationName:kDownloadVideoStateChangeNotification object:model userInfo:nil];
    }
```

**Comment by OCer** [comment]
解决了
