### ISSUE TITLE
感谢分享这么优秀的开源库

### ISSUE THREAD

**Issue by SuperManPLA** [onezens/YCDownloadSession#18]
问一下，可以自定义下载路径么

**Comment by onezens** [comment]
谢谢，目前是不支持的，待会儿我添加一个入口

**Comment by SuperManPLA** [comment]
好的，谢谢，onezens威武。

**Comment by onezens** [comment]
1. 自定义下载数据存储根路径的入口：
 https://github.com/onezens/YCDownloadSession/blob/c154d168e4891aff34cda1689707d17d9192d8fa/YCDownloadSession/AppDelegate.m#L52
2. 如果想要再次自定义下载数据，自己指定YCDownloadTask的savePath属性，YCDownloadItem是savePath属性时只读，要想自定义该属性，到demo 里的YCDownloadInfo里面重写父类方法
