### ISSUE TITLE
下载视频  》暂停 》 再开始  会崩溃

### ISSUE THREAD

**Issue by hupfei** [onezens/YCDownloadSession#19]
![default](https://user-images.githubusercontent.com/8318751/38969774-822ecda8-43c4-11e8-905e-f17a900c463b.png)
视频地址https://mp4.1sj.tv/mp4/78b31daf2731ea0d491af530b6f4bde7.mp4
求解

**Comment by onezens** [comment]
iOS 系统？ 设备型号？

**Comment by hupfei** [comment]
iphone6 ios11.3

**Comment by onezens** [comment]
是clone的最新代码吗？不是的话，使用最新的代码

**Comment by hupfei** [comment]
最新的代码  其他的视频下载正常  其他的手机也正常。。。
