### ISSUE TITLE
下载停止情况

### ISSUE THREAD

**Issue by QiuXiaochun** [onezens/YCDownloadSession#2]
1.建议博主把本地通知的名称更改一下,改换成 配置后台下载 identifier 的形式.
2.设置最大下载数是不是必须的.有这么一种情况,当添加了两个下载任务,未设置最大下载数,显示只有一个在刷新的下载.这个时候退到后台,我们什么都不管该APP,在某个时候进去,早先开始下载的那个已经下载完成了,剩下一个不动了.必须手动点击两次才刷新下载.进去的时候是显示了启动页的,时间不短,是不是因为后台杀死了,下载单例已经干掉了?下载文件大小200M-300M 不等.而且有的时候,通过点击启动的下载的文件有不完整的情况.

**Comment by QiuXiaochun** [comment]
其实最纠结的问题就是,退出后台,过段时间进来,任务显示是正在下载状态,但是 UI 进度没有及时刷新,在那里不动,这个是最蛋疼的.然后用户有可能会点来点去,然后UI动了,但是有可能下载的文件有问题.

**Comment by onezens** [comment]
1. 不考虑了，感觉没必要
2. 请说明机型， 系统， 是本demo下载过程中暂停？是不是下载的最新代码？

**Comment by QiuXiaochun** [comment]
第一个其实我也觉得无所谓.上周五下载的demo,如果用你的下载接口是不存在这个问题的,因为demo中的文件大小很小,发现不了这个问题,所以接入了别的下载接口.文件都是200M平均.就是有的时候进度条无法及时刷新,显示正在下载状态.

**Comment by QiuXiaochun** [comment]
IPHONE SE, 11.0.3

**Comment by QiuXiaochun** [comment]
还有感谢楼主的回复.

**Comment by onezens** [comment]
我看你描述的问题像以前的就代码，你从GitHub下载最新的试试，我测试了好几次，没有发现有相关的现象，如果新的代码还有问题的话，给我截个图看看，我看看UI

**Comment by onezens** [comment]
也谢谢你的反馈

**Comment by QiuXiaochun** [comment]
好的.

**Comment by onezens** [comment]
我的邮箱 mail@onezen.cc

**Comment by QiuXiaochun** [comment]
楼主你好,刚用了一下最新的代码,我首先接线状态是可以下载的,有个小问题,就是缓存删除会闪退.然后我们重新安装,拔掉数据线,下载数不设置默认一个,我们添加3个任务,一个正在下载,两个在等待,这个时候我们推出去看书了,让它下载,中间收到一个本地推送,一个应该是在推出的时候已经下载好了,然后还有最后一个,我们进去看,下载显示完成,但是数据有问题.这是拔掉线发现的.
![screen shot 2017-10-24 at 1 35 26](https://user-images.githubusercontent.com/18690958/31926534-9d143268-b8c1-11e7-9727-2274457c335f.png)
![screen shot 2017-10-24 at 1 35 34](https://user-images.githubusercontent.com/18690958/31926535-9d49ef7a-b8c1-11e7-8fed-da8233c2d1ba.png)

**Comment by onezens** [comment]
缓存删除会闪退 和 视频找不到的问题解决了，你下载新的再试试

**Comment by QiuXiaochun** [comment]
好的啊.
