### ISSUE TITLE
下载的视频会自动清除？

### ISSUE THREAD

**Issue by renwoxing** [onezens/YCDownloadSession#21]
我下载了很多的视频 zip 文件，不知道什么时候会删除？

**Comment by onezens** [comment]
如何问问题了解一下

**Comment by onezens** [comment]
1. 查看手机剩余磁盘空间。YCDownloadSession 默认数据保存在Cache路径，如果空间不足，会被系统清理掉，如果不想被清理掉，请自定义保存路径。
2. 如果磁盘空间足够，请debug/NSLog追踪下删除任务的方法
