### ISSUE TITLE
下载功能，断网联网多次出现下载失败之后，重启APP再次进入界面闪退

### ISSUE THREAD

**Issue by WowJesse** [onezens/YCDownloadSession#25]
**手机信息 (please complete the following information):**  
 - Device: 6P
 - OS:iOS10.3
 - YCDownloadSession Version 最新版本

**如何复现**  
下载功能，断网联网多次出现下载失败之后，重启APP再次进入下载列表界面闪退

**错误或者奔溃信息**  
Attempted to create a task in a session that has been invalidated
Trapped uncaught exception 'NSGenericException', reason: 'Task created in a session that has been invalidated' 

**友情提示**  
断点在了   YCDownloadSession.m的404行
NSURLSessionDownloadTask *downloadTask = [self.session downloadTaskWithRequest:request];

**Comment by onezens** [comment]
测试多次，都没有复现。根据错误信息，是WiFi和蜂窝煤网络切换的时候task状态异常的问题

这个问题在你手机上面复现的几率高吗？

**Comment by WowJesse** [comment]
好像是我使用问题。

**Comment by SuperManPLA** [comment]
这个问题我也遇到过，复现率很高，不用切换WiFi和蜂窝，只多次切换WiFi就会出现，我加了个try

**Comment by SuperManPLA** [comment]
多次切换WiFi，不光会出现崩溃，加个try能避免，还会出现2个task下载一个任务的情况，导致有2个下载进度

**Comment by WowJesse** [comment]
我缓存20个视频，打开缓存列表。80%又出现这个问题

**Comment by WowJesse** [comment]
@onezens 没切换，就是缓存多个之后，再打开缓存列表，80%报错

**Comment by WowJesse** [comment]
@SuperManPLA 老哥，能否提供下你的try代码。我加了try还是崩溃

**Comment by onezens** [comment]
是不是有切换网络状态？同时下载任务个数是多少个？

**Comment by WowJesse** [comment]
@onezens 没切换，一直WIFI，下载20个，有一部分下载完 ，一部分正在下载期间。崩溃

**Comment by onezens** [comment]
fix it 2.0.0 

https://github.com/onezens/YCDownloadSession/blob/dev/YCDownloadSession/YCDownloader.m#L148
