### ISSUE TITLE
关掉应用再次打开任务列表全部变为暂停状态，一路追踪下来定位到URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error

### ISSUE THREAD

**Issue by SoulmateL** [onezens/YCDownloadSession#26]
**手机信息 (please complete the following information):**  
 - Device: [e.g. iPhone6s]
 - OS: [e.g. iOS11.2.1]
 - YCDownloadSession Version [最新版]

**如何复现**  
详细的描述如何复现返回的问题？并且参照demo，在demo里同样的操作是否会复现？
1. 重复关掉开启应用偶尔出现任务列表全部变为暂停状态，然后任务就无法被下载了，新增的任务一样无法下载

**错误或者奔溃信息**  
在使用NSURLSession进行后台下载的时候,有时候didCompleteWithError方法会出现 Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSErrorFailingURLStringKey=http://********,

![d56c4696-6a45-4e82-9c69-088d50267f5a](https://user-images.githubusercontent.com/23186926/39658635-e340eee6-5049-11e8-82f4-4d2191e5ca91.png)

**Comment by onezens** [comment]
手动杀死App，系统默认会暂停所有后台任务

**Comment by jeff201903** [comment]
一样的问题，请问怎么解决？

**Comment by ranhelei** [comment]
@jeff201903 你好这个问题解决了吗
