### ISSUE TITLE
已经下载完成的任务，有时重新打开APP会出现在未完成的数组里面

### ISSUE THREAD

**Issue by SoulmateL** [onezens/YCDownloadSession#27]
**手机信息 (please complete the following information):**  
 - Device: [e.g. iPhone6s]
 - OS: [e.g. iOS11.2.1]
 - YCDownloadSession Version [最新版]

**如何复现**  
比如我现在一个视频A下载完成了，我退出APP后再打开，偶尔会出现已完成的视频A的状态变成未完成状态

**Comment by onezens** [comment]
注意url和fileid保持一一对应
