### ISSUE TITLE
最新版stopDownloadWithItem方法出错

### ISSUE THREAD

**Issue by hupfei** [onezens/YCDownloadSession#28]
删除文件时，文件时删除了，但是本地序列化文件并没有删除

**Comment by onezens** [comment]
通过demo测试没有问题，请断点调试stopDownloadWithItem方法，查看删除路径是否正确

**Comment by hupfei** [comment]
调过了  只是删除了视频文件  本地保存的下载信息没有删除
而且stopDownloadWithItem方法中是不是应该调用[self.itemsDictM removeObjectForKey:itemId]？

**Comment by onezens** [comment]
是

**Comment by hupfei** [comment]
但是你没有调用啊

**Comment by onezens** [comment]
谢谢反馈，这个问题，在一个月前已经修复了，是这个commit：

https://github.com/onezens/YCDownloadSession/commit/c154d168e4891aff34cda1689707d17d9192d8fa#diff-32de14fc19f82189b281ab79cfe7a5d3R281

**Comment by onezens** [comment]
你是通过pods安装的吗？

**Comment by hupfei** [comment]
抱歉 没及时更新  你8天前加了这句

**Comment by hupfei** [comment]
pod安装的

**Comment by onezens** [comment]
嗯，稍后我更新下pod

**Comment by hupfei** [comment]
pod上面不是最新代码啊

**Comment by onezens** [comment]
🚀  YCDownloadSession (1.2.5) successfully published
 📅  May 10th, 22:27
 🌎  https://cocoapods.org/pods/YCDownloadSession

**Comment by hupfei** [comment]
国外？
