### ISSUE TITLE
下载的时候来回切换下载，暂停，下载出来的视频无法播放

### ISSUE THREAD

**Issue by LChao05** [onezens/YCDownloadSession#3]
下载的时候来回切换下载，暂停，下载出来的视频无法播放，这个问题在demo中必现。

**Comment by onezens** [comment]
来回切换下载是什么操作？

**Comment by LChao05** [comment]
就是点击下载的时候缓存页的cell不停点击

**Comment by LChao05** [comment]
而且删除这一行cell再点击下载这个视频的时候直接显示下载完成，大小是0B

**Comment by onezens** [comment]
谢谢反馈，已经解决了，重新下载试试 @17671621757

**Comment by onezens** [comment]
刚刚解决了一个视频找不到的问题，重新下载试试

**Comment by LChao05** [comment]
正在下载的时候，再快速不停的点击缓存页的正在下载的cell（在下载完成前不停的点击），导致下载出来的视频无法播放，这个问题还存在

**Comment by onezens** [comment]
重新下载试试

**Comment by LChao05** [comment]
下载成功的视频再点击下载的时候又重头下载了一次

**Comment by onezens** [comment]
你下载最新代码了没有， 下载最新代码试试。  然后把原先的app删掉，这个问题早上解决了

**Comment by LChao05** [comment]
就是最新代码，我是这样操作的，在下载的时候不停点击cell ，发现视频下载完了但是进度没到头，这个时候返回再去下载这个视频就会出现这样的情况，你多试几次这样的问题必现

**Comment by onezens** [comment]
我都试了很多次， 没有发现这个问题。 你要是能试出来，自己调试下代码，对你来说也是个锻炼

**Comment by onezens** [comment]
@17671621757 这个问题刚刚解决了，是iOS 11.0.2的问题，文件大小不对，但是苹果sdk回调成功。 当时我手机两个手机系统是：ios 9.3.2 和ios10.3所以测试多次，没有发现该问题。 解决的办法是：回调失败，重新下载。 这个应该是苹果SDK的bug，我会反馈给苹果，看以后版本是否会解决。
