### ISSUE TITLE
bug 反馈 

### ISSUE THREAD

**Issue by SuperManPLA** [onezens/YCDownloadSession#30]
**手机信息 (please complete the following information):**  
 - Device: [e.g. iPhone6] [e.g. iPhone8] [e.g. iPhoneX]
 - OS: [e.g. iOS8.3][e.g. iOS10.3.2][e.g. iOS11.3]
 - YCDownloadSession Version [e.g. 1.2.5]

**如何复现**  
详细的描述如何复现返回的问题？并且参照demo，在demo里同样的操作是否会复现？
1. 到下载页面
2. 点击下载
3. App进入后台，频繁切换WiFi，每次切换后进入App

**错误或者奔溃信息**  
出现2个task下载一个任务的情况，控制台会打印2个下载进度，导致下载出错或者失败，UI异常。

这个bug是偶现的，且概率很大，demo里一样会复现。

**Comment by onezens** [comment]
新版本修复 2.0.0
