### ISSUE TITLE
针对一些比较奇怪的下载地址，需要做特殊判断

### ISSUE THREAD

**Issue by LinJiaXing1102** [onezens/YCDownloadSession#31]
例如这个下载地址：http://61.131.79.30:8085/uer-repo1/8fc9b66e13344182bc2a9ff4a188512.xlsx?response-content-disposition=attachment%3Bfilename%3D%E6%96%B0%E5%BB%BA%20Microsoft%20Excel%20%E5%B7%A5%E4%BD%9C%E8%A1%A8.xlsx&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20180516T084350Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=NRJ4WJKDYWIIM0993CF6%2F20180516%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=d61bb81a330e47834011ed5b755db7110cc8556017ab13cf807c313e9f385dd6

再经过 `- (NSString *)getPathExtensionWithUrl:(NSString *)url`这个方法的时候，不能取到正确的后缀名

打断点发现 经过`NSString *pathExtension = [url pathExtension];`获取到的文件后缀变成了
`xlsx&response-content-...(省略)`

也就是说 `?` 变成了 `&` , 虽然我也搞不懂什么问题...

所以修改了一下 `- (NSString *)getPathExtensionWithUrl:(NSString *)url` 这个方法

```objc
+ (NSString *)getPathExtensionWithUrl:(NSString *)url {
    NSString *pathExtension = [url pathExtension];
    NSArray *pathExtensionArray = [pathExtension componentsSeparatedByString:@"&"];
    //过滤url中的参数，取出单独文件名
    NSRange range = [pathExtension rangeOfString:@"?"];
    if (range.location>0 && range.length == 1) {
        pathExtension = [pathExtension substringToIndex:range.location];
    } else if (pathExtensionArray.count > 0 ) {
        pathExtension = pathExtensionArray.firstObject;
    }
    return pathExtension;
}
```

**Comment by onezens** [comment]
赞， 谢谢反馈，通过另外一种方式解决这个问题了。

https://github.com/onezens/YCDownloadSession/blob/fa73bbac3af37489d6ffd6ece97ee00311038464/YCDownloadSession/YCDownloadSession/YCDownloadTask.m#L276
