### ISSUE TITLE
Session程序崩溃后，重新启动程序！后台下载还是在进行

### ISSUE THREAD

**Issue by ZY-Merry** [onezens/YCDownloadSession#33]
Session程序崩溃后，重新启动程序！后台下载还是在进行，这样我开始原来的下载，会有两个相同的NSURLSessionDownloadTask进行，但是他们都可以找到 YCDownloadTask *task = [self getDownloadTaskWithUrl:[YCDownloadTask getURLFromTask:downloadTask]];同一个YCDownloadTask，如何避免这种问题？

**Comment by onezens** [comment]
下载库版本？

https://github.com/onezens/YCDownloadSession/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md
