### ISSUE TITLE
非手动杀死app（崩溃或者stop the running scheme or application），出现bug

### ISSUE THREAD

**Issue by ZY-Merry** [onezens/YCDownloadSession#34]
**手机信息 (please complete the following information):**  
 - Device: iPad，iPhone所有型号
 - YCDownloadSession Version [1.2.5]

**如何复现**  
1、运行程序，开始一个下载
2、停止程序运行（stop the running scheme or application），非手动杀死app，所以后台任务继续下载
3、重新启动程序 ，开始相同的下载（此时原来的后台任务还在下载）
4、- (void)URLSession:(NSURLSession *)session
      downloadTask:(NSURLSessionDownloadTask *)downloadTask
      didWriteData:(int64_t)bytesWritten
 totalBytesWritten:(int64_t)totalBytesWritten
totalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite 
在此方法中，有两个downloadTask 根据 YCDownloadTask *task = [self getDownloadTaskWithUrl:[YCDownloadTask getURLFromTask:downloadTask]];找到了同一个YCDownloadTask，task.downloadedSize出现异常，表现下载进度闪烁

这样，如果出现崩溃现象，再次启动就可能出现这个bug！请问怎样处理这种bug？

**Comment by SuperManPLA** [comment]
不用闪退，崩溃，频繁切换wifi环境，也会出现2个task下载一个任务，下载进度闪烁在2个进度之间，跟我提的bug是同一个。

**Comment by ZY-Merry** [comment]
那你是怎么处理这个问题的呢？ @SuperManPLA

**Comment by onezens** [comment]
新版本修复 2.0.0
