### ISSUE TITLE
出现 Task created in a session that has been invalidated 崩溃

### ISSUE THREAD

**Issue by SoulmateL** [onezens/YCDownloadSession#35]
![image](https://user-images.githubusercontent.com/23186926/40948717-90a0360e-689c-11e8-818f-187448487e65.png)

 - YCDownloadSession 最新版

**如何复现**  
![image](https://user-images.githubusercontent.com/23186926/40948696-75e89a36-689c-11e8-8896-55c26643000b.png)

**Comment by onezens** [comment]
fix it 2.0.0

https://github.com/onezens/YCDownloadSession/blob/ea15b9dea50ea005a365859049cd20fb13aa229b/YCDownloadSession/YCDownloader.m#L148
