### ISSUE TITLE
问题有点多

### ISSUE THREAD

**Issue by yexiwen** [onezens/YCDownloadSession#4]
1、有fileid不能暂停、恢复
2、删除没有删掉文件
3、后台下载不能继续下载等待任务
4、多次暂停恢复，直接下载就成功了
5、正在下载闪退后，重新点下载没有断点续下

**Comment by onezens** [comment]
提问题的时候，希望你能够下载最新代码，重新试试，谢谢合作。你这些问题都是好几周之前已经解决过的！
