### ISSUE TITLE
请问如何添加视频下载的请求头呢？

### ISSUE THREAD

**Issue by SoulmateL** [onezens/YCDownloadSession#41]
希望添加视频下载的请求头，谢谢

**Comment by Baiyongyu** [comment]
同问！查了一些文，说是需要请求头，加个什么Range  ，如何在框架里添加啊

**Comment by Baiyongyu** [comment]
找到了，是不是这个，已经处理好了。
<img width="675" alt="image" src="https://user-images.githubusercontent.com/18496805/41805126-af9da608-76d5-11e8-999d-5e2457df34cb.png">

**Comment by SoulmateL** [comment]
不是这个吧，你怎么解决的呢

**Comment by Baiyongyu** [comment]
这个应该就是的 请求头range什么的 不就是这个吗

**Comment by onezens** [comment]
这里是创建request的地方，你们可以在这个request里面加请求头

https://github.com/onezens/YCDownloadSession/blob/47a7a070777899ec294f4d674baa4a007369ffbb/YCDownloadSession/YCDownloadSession/YCDownloadSession.m#L314

**Comment by onezens** [comment]
修改下载task的range是件很麻烦的事情，断点续传的resumeData里面记录了request的相关数据 @Baiyongyu

**Comment by Baiyongyu** [comment]
好的 谢谢
