### ISSUE TITLE
App退到后台task 调用dealloc，任务失败

### ISSUE THREAD

**Issue by SoulmateL** [onezens/YCDownloadSession#42]
**手机信息 (please complete the following information):**  
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS11.4]
 - YCDownloadSession Version [1.2 6]

**如何复现**  
demo也会出现这个问题  在下载过程中直接进入后台  任务dealloc了

**错误或者奔溃信息**  
复制粘贴相关信息或者截图

**友情提示**  
发生问题，或者有疑问时，**请仔细参照demo的实现逻辑**。为了能够快速解决，请严格按照本模板描述，并且将你的问题在demo的复现过程详细描述出来。

有能力的同学，请自行debug问题的原因，然后进行反馈。或者找到解决办法后发起pull request。

**Comment by onezens** [comment]
fixed 25bb60e84042802020871a35447a02fc35688428
