### ISSUE TITLE
从后台返回到App下载状态混乱，会出现全部任务同时下载的情况

### ISSUE THREAD

**Issue by SoulmateL** [onezens/YCDownloadSession#43]
**手机信息 (please complete the following information):**  
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS11.4]
 - YCDownloadSession Version 最新版

**如何复现**  
详细的描述如何复现返回的问题？并且参照demo，在demo里同样的操作是否会复现？
添加多个任务到下载列表，设置同时最大下载数为3，然后退到后台，等几分钟进入App，会出现全部任务同时下载的情况并且有可能会出现状态混乱的情况

**错误或者奔溃信息**  
复制粘贴相关信息或者截图

**友情提示**  
发生问题，或者有疑问时，**请仔细参照demo的实现逻辑**。为了能够快速解决，请严格按照本模板描述，并且将你的问题在demo的复现过程详细描述出来。

有能力的同学，请自行debug问题的原因，然后进行反馈。或者找到解决办法后发起pull request。

**Comment by onezens** [comment]
fixed 25bb60e84042802020871a35447a02fc35688428
