### ISSUE TITLE
修改下载路径

### ISSUE THREAD

**Issue by sunlei4076** [onezens/YCDownloadSession#47]
现在下载的路径是在沙盒里的cache里？
可以修改为document文件夹吗

**Comment by sunlei4076** [comment]
@onezens

**Comment by onezens** [comment]
可以设置保存路径

https://github.com/onezens/YCDownloadSession/blob/ea15b9dea50ea005a365859049cd20fb13aa229b/YCDownloadSession/YCDownloadManager.h#L25
