### ISSUE TITLE
我一直想让它 出现那种在通知栏上   在appdelegate 里面断点打上却没有走 。   跑的就是这个开源的demo  我换了个mp4的视频，有40分钟的样子 

### ISSUE THREAD

**Issue by 835932621** [onezens/YCDownloadSession#48]
**手机信息 (please complete the following information):**  
 - YCDownloadSession Version [e.g. 22]

**如何复现**  
详细的描述如何复现返回的问题？并且参照demo，在demo里同样的操作是否会复现？
1. 到xx页面
2. 点击xx
3. 出现xx错误

**错误或者奔溃信息**  
复制粘贴相关信息或者截图

**友情提示**  
发生问题，或者有疑问时，**请仔细参照demo的实现逻辑**。为了能够快速解决，请严格按照本模板描述，并且将你的问题在demo的复现过程详细描述出来。

有能力的同学，请自行debug问题的原因，然后进行反馈。或者找到解决办法后发起pull request。

**Comment by onezens** [comment]
后台下载想要回调通知，需要等当前URLSession 所有的task完成后才会激活APP，触发断点。单个是不会触发，而且不同的系统版本会有不同的结果
