### ISSUE TITLE
防盗链url 改变下载路径

### ISSUE THREAD

**Issue by dong136279559** [onezens/YCDownloadSession#51]
您好,请问我们公司的下载url 是加了防盗链的,一个小时改变一次,我想问一下,我使用YCDownloadSession 的时候应该如何在下载失败的时候判断过期,然后重新生成下载呢,或者有没有更简单一点的办法呢?

**Comment by fuadam1982** [comment]
我是直接修改了源码，在YCDownloadTask中加了个realDownloadURL的属性。然后在入口的地方加了一个验证token的block，然后依次在所有使用downloadURL的地方加上对realDownloadURL的处理

**Comment by dong136279559** [comment]
能否考虑给作者提交一下代码呢?这样可以使YCDownloadSession功能更加完善,能帮助更多开发者.

**Comment by fuadam1982** [comment]
@dong136279559 这个功能是强行加上去的，从整体上来讲代码风格并不好。我觉得应该由作者重构后加上这种功能比较好
