### ISSUE TITLE
app 后台运行问题

### ISSUE THREAD

**Issue by Shameless521** [onezens/YCDownloadSession#52]
**手机信息 (please complete the following information):**  
 - OS: [e.g. iOS9.3]
 - YCDownloadSession Version [最新版本]

**如何复现**  
开启下载任务后，APP切换到后台，在唤醒以后，下载任务不继续。

demo 也是这个问题。

**Comment by onezens** [comment]
自测没有问题，希望能够提供更多信息

**Comment by ZL335408** [comment]
我也遇到同样的问题，是在真机情况下不要太快的切换前后台就会出现这种情况。然后多切换几次就又恢复了
