### ISSUE TITLE
非200处理

### ISSUE THREAD

**Issue by dongwwei** [onezens/YCDownloadSession#53]
感谢分享！！看了几天源代码，有一些问题指出来，望修正：
1.下载没有对非200的情况进行处理（没有对接收到响应这个回调进行处理），导致下载地址是错误的还能把错误的信息写入文件。
2.我用的版本是YCDownloadSession（1.2.3），在初始化Session的时候并没有暂停所有下载，导致手动杀掉app会暂停，但是通过xcode杀掉或者程序crash下次启动app状态还是正在下载。
3.类型转换有问题，content-length是long long类型，直接把已下载大小（downloadedSize）和文件大小（fileSize）用nsinter类型强转，这样导到32位机型nsinter会超出取值范围，只能下载2G以下的视频。
4.没有对302重定向进行处理

**Comment by onezens** [comment]
非常感谢这么用心的反馈，这些问题我会在新版本中修改，但是由于个人精力问题 `1.X` 版本将不会更新了

**Comment by onezens** [comment]
2.0.0 版本

1.  非200已经处理
2.  这个是系统默认退出后会自动下载，目前没有发现有相关api可以取控制
3.  已经处理
4.  2.0.0 测试301、302正常下载
