### ISSUE TITLE
Some Functionalities not working with iOS 10 and iOS 12.

### ISSUE THREAD

**Issue by HemenduK** [onezens/YCDownloadSession#54]
**手机信息 (please complete the following information):**  
 - OS: [e.g. iOS 10.3.2] & iOS 12
 - YCDownloadSession Version [e.g. 2.0.0]

in iOS 11 all the functionalities working fine but i find below issues.

1. in iOS 10.3.2 After completion of video download it's giving state failed instead of finished.
because the file is not able to move to document directory.
**func downloadItemStatusChanged(_ item: YCDownloadItem)**

2. in iOS 12 I paused a video and then i am not able to resume same video.

Please resolve ASAP.
Thank you.

**Comment by onezens** [comment]
Any error log can show me ? or you download url let me test

I use my demo test download function with iOS 10 & iOS 12 all works

**Comment by HemenduK** [comment]
I have tried with this URL : http://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_1920_18MG.mp4

1. in iOS 12 first check with pause the video and resume it .....issue is it will not resume.
2. in iOS 10 same above issue and second issue is in iOS 10.3.2 After completion of video download it's giving state failed instead of finished.
because the file is not able to move to document directory.
func downloadItemStatusChanged(_ item: YCDownloadItem)

**Comment by onezens** [comment]
> I have tried with this URL : http://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_1920_18MG.mp4
> 
> 1. in iOS 12 first check with pause the video and resume it .....issue is it will not resume.
> 2. in iOS 10 same above issue and second issue is in iOS 10.3.2 After completion of video download it's giving state failed instead of finished.
>    because the file is not able to move to document directory.
>    func downloadItemStatusChanged(_ item: YCDownloadItem)

I use your resource url and latest repo code, iOS 12 pause it and resume it .... all works,  

Did you use the latest code? 

If you use latest code and resume failed then Xcode console should have some debug logs, and you can paste is here

**Comment by HemenduK** [comment]
Yes I am using latest code I have attached file here ... Also i have checked with your sample code i am attaching video.
[Screen Recording.zip](https://github.com/onezens/YCDownloadSession/files/2460464/Screen.Recording.zip)
 
[YCLog.pdf](https://github.com/onezens/YCDownloadSession/files/2460457/YCLog.pdf)

**Comment by onezens** [comment]
I see you log download task resume success, I guess because of the network so pause and resume download have no obvious change, the case is resume slowly.

You can see my record video , iOS 12 iPhone Xs-Max resume download works, and log: `task resumedata success`

[download-test-xs-max.mp4.zip](https://github.com/onezens/YCDownloadSession/files/2463279/download-test-xs-max.mp4.zip)

**Comment by onezens** [comment]
HD video：  
https://ycpu.oss-cn-beijing.aliyuncs.com/video/test-download-xs-max.mp4

And you can insert a breakpoint `po downloadTask.state`, If state is `NSURLSessionTaskStateRunning`  prove the task resume succeed and you will wait a minute will progress the task

<img width="1320" alt="download" src="https://user-images.githubusercontent.com/15090427/46716236-ca3d2b80-cc95-11e8-9259-3a907f944f42.png">

**Comment by onezens** [comment]
I add some code for resume data, you can use latest master branch code , test resume and see logs

https://github.com/onezens/YCDownloadSession/commit/82a71f115ba8e5ee5243af5e1b601ae9de60df63
