### ISSUE TITLE
有些视频链接不能下载

### ISSUE THREAD

**Issue by LirunCode** [onezens/YCDownloadSession#55]
我用demo 下载 http://vod8ujdpyrm.vod.126.net/vod8ujdpyrm/942042cd-3bc4-4cc4-8a8e-6c4e7e9d9e8a.mp4  这个链接地址下载一直失败!
![image](https://user-images.githubusercontent.com/17909555/46724239-2f038080-ccac-11e8-93f7-5e3cffeb19e9.png)

**Comment by onezens** [comment]
下载master最新代码， 已经解决

**Comment by LirunCode** [comment]
还有个小问题,正在下载的时候强制关掉app, 再次进入app 状态一直是正在下载,但是这时候并没下载, 这种状态应该是暂停中吧

**Comment by onezens** [comment]
是在下载， 部分app死掉情况下，系统会默认在后台下载；正常退出应该是不会
