### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by dong136279559** [onezens/YCDownloadSession#58]
需求问题

问题:我要对已完成数据进行分层筛选,需要parentId等额外属性,如果设置extraData的话,二进制数据解析比较浪费时间.

能否在YCDownloadItem 中添加3个额外的string字段(extraStr1,extraStr2,extraStr3)用来进行少量数据保存,再多的话就使用extraData进行较多数据的保存.

谢谢.

**Comment by dong136279559** [comment]
作者您好,请问我这样的想法在2.0.1会增加吗?如果觉得可行,您觉得什么时候能够增加上呢,如果不行,我这边就考虑其他的实现方式了,您能回复下吗?@onezens

**Comment by onezens** [comment]
这种方式感觉不太好，等我想到好的办法有可能会加的，但是近期比较忙，估计不会加的

**Comment by dong136279559** [comment]
那我只能解析二进制数据来进行判断了吗?我觉得之前1.0版本的时候那个继承关系挺好用的,现在2.0的话,设置extraData确实有点麻烦,我这如果需要对保存的数据进行分级的话,您有什么好的建议呢?

**Comment by dong136279559** [comment]
@onezens 您能给我的项目需求提一点建议吗?我确实需要一些方法来进行这个功能的处理?

**Comment by onezens** [comment]
我打算通过继承的思路来做你的这个需求，你目前可以通过extraData来做，在获取数据时，可以做个桥梁类来做个转换
桥梁类实现逻辑：
将extraData中的json数据，转换成你需要的Object，然后对这个转换好的Object进行排序分类
