### ISSUE TITLE
iOS11 bug

### ISSUE THREAD

**Issue by jiangchao829** [onezens/YCDownloadSession#6]
iOS11 bug  因为ios11上的 resumeData 有改动 改了这个就好了

**Comment by onezens** [comment]
iOS 11.2 官方已解决， iOS 11.1 修改resumeData是不错的解决办法，谢谢提醒

**Comment by onezens** [comment]
如果你使用的话，在11.2最好处理，只在iOS 11一处resume data range，因为11.2有NSURLSessionResumeByteRange 是正常的，说不一定在以后版本会使用到

修复记录： https://github.com/onezens/YCDownloadSession/pull/9
