### ISSUE TITLE
当下载不支持的url时崩溃的问题

### ISSUE THREAD

**Issue by SSLoong** [onezens/YCDownloadSession#66]
今天在测试的时候 选错了环境 导致下载的所有url都是无效的 后来发现在下载无效的url时 会出现crash的问题。这是控制台日志：
 [didCompleteWithError] : Error Domain=NSURLErrorDomain Code=-1002 "不支持的 URL" UserInfo={NSErrorFailingURLKey=www.12345qwert.zip, NSErrorFailingURLStringKey=www.12345qwert.zip, NSLocalizedDescription=不支持的 URL}
2018-11-20 14:27:52.525448+0800 app-chinese-study-iPad[4334:1551349] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM removeObjectForKey:]: key cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105ee01bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010547e735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105e2c4ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000105f51d45 -[__NSDictionaryM removeObjectForKey:] + 213
	4   YCDownloadSession                   0x0000000104e16e5b -[YCDownloader removeMembCacheTask:task:] + 155
	5   YCDownloadSession                   0x0000000104e16f82 -[YCDownloader completionDownloadTask:localPath:error:] + 226
	6   YCDownloadSession                   0x0000000104e196dd -[YCDownloader URLSession:task:didCompleteWithError:] + 1165
	7   CFNetwork                           0x00000001077fa342 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.241 + 284
	8   Foundation                          0x0000000104eebf9e __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   Foundation                          0x0000000104eebea5 -[NSBlockOperation main] + 68
	10  Foundation                          0x0000000104ee8c14 -[__NSOperationInternal _start:] + 689
	11  Foundation                          0x0000000104eeec4b __NSOQSchedule_f + 227
	12  libdispatch.dylib                   0x00000001082d1046 _dispatch_block_async_invoke2 + 83
	13  libdispatch.dylib                   0x00000001082c3602 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00000001082d099a _dispatch_main_queue_callback_4CF + 1541
	15  CoreFoundation                      0x0000000105e453e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x0000000105e3fa76 __CFRunLoopRun + 2342
	17  CoreFoundation                      0x0000000105e3ee11 CFRunLoopRunSpecific + 625
	18  GraphicsServices                    0x000000010f0a01dd GSEventRunModal + 62
	19  UIKitCore                           0x0000000109e7681d UIApplicationMain + 140
	20  YCDownloadSessionDemo               0x000000010496aa10 main + 112
	21  libdyld.dylib                       0x0000000108339575 start + 1
)

在demo上我看了下，感觉是YCDownloader.m中 这个方法的问题 
- (void)removeMembCacheTask:(NSURLSessionDownloadTask *)downloadTask task:(YCDownloadTask *)task {
    task.stid = -1;
   //downloadTask为空了
    [self.memCache removeObjectForKey:downloadTask];
}
我现在在下载前加了个url的校验，不支持的url都不进行下载了，不过希望大佬可以看一下，到底是什么原因导致的。谢谢

**Comment by onezens** [comment]
最新版本2.0.1没有这个问题，更新最新代码的试试

**Comment by SSLoong** [comment]
大佬您好，我在项目里使用的就是最新版2.0.1 
```
github "onezens/YCDownloadSession" "2.0.1"

```
另外我在您的Demo里也试了下，在VideoListInfoController.m文件中把下载的URL换成www.12345qwert.zip这种乱写的URL 也同样会出现这个问题，
```
- (void)videoListCell:(VideoListInfoCell *)cell downloadVideo:(VideoListInfoModel *)model {
    YCDownloadItem *item = nil;
    if (model.file_id) {
        item = [YCDownloadManager itemWithFileId:model.file_id];
    }else if (model.mp4_url){
        item = [YCDownloadManager itemsWithDownloadUrl:model.mp4_url].firstObject;
    }
    if (!item) {
        //改成不支持的URL
        item = [YCDownloadItem itemWithUrl:@"www.12345qwert.zip" fileId:model.file_id];
        item.extraData = [VideoListInfoModel dateWithInfoModel:model];
        [YCDownloadManager startDownloadWithItem:item];
    }
    VideoCacheController *vc = [[VideoCacheController alloc] init];
    [self.navigationController pushViewController:vc animated:true];
}
```
具体原因我就不太明白了，您可以看下，  谢谢大佬。

**Comment by onezens** [comment]
我这边用最新的代码，用`www.12345qwert.zip`下载就正常回调失败了，不会奔溃，而且我看你的奔溃栈的代码行数和最新代码行数对不上，所以问代码是不是最新的？

希望能够提供下能够和最新代码行数对上的奔溃信息

**Comment by SSLoong** [comment]
我更新了最新的代码， 就没有这个问题了 ，谢谢大佬。应该是我demo里pull的2.0.1但是项目里carthage编译的还是旧代码，麻烦大佬了。
