### ISSUE TITLE
mgrWithConfig创建的是单例，重新设置config不会生效

### ISSUE THREAD

**Issue by PengKezhu** [onezens/YCDownloadSession#73]
+ (void)mgrWithConfig:(YCDConfig *)config {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _instance = [[self alloc] init];
        YCDownloadMgr.config = config;
        [YCDownloadMgr initManager];
    });
}

**Comment by onezens** [comment]
部分设置是在初始化时已经配置，再次设置会不生效
生效的话需要刷新所有任务
