### ISSUE TITLE
后台切换到前台下载界面卡住了

### ISSUE THREAD

**Issue by ZL335408** [onezens/YCDownloadSession#74]
发现当处于下载列表中下载任务时将APP退到后台模式然后重新回到APP前台（不要切换的太快大概10s左右），发现所有下载列表中正在下载的任务界面都卡死了但是后台的下载任务还在进行，下载速度和进度这些的代理不走了。重复前后台切换几次后概率性的界面又恢复了。

**Comment by onezens** [comment]
重写一版本
