### ISSUE TITLE
下载失败的任务重复出现问题

### ISSUE THREAD

**Issue by ZL335408** [onezens/YCDownloadSession#76]
点击下载失败的任务重新下载然后强制重启app，下载列表会出现一条一样的下载任务。重复该操作下去同样的下载任务会一直增加下去

**Comment by ZL335408** [comment]
目前我这边的解决办法是：对于下载失败的任务重新调用下载时先进行删除，隔1s后再调用下载就不会出现重复的内容了

**Comment by onezens** [comment]
mater分支最新代码已解决

**Comment by onezens** [comment]
请提供详细的可复习操作
