### ISSUE TITLE
关于下载速度显示的问题

### ISSUE THREAD

**Issue by XiaoYiS** [onezens/YCDownloadSession#77]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/15341057/51017513-4144d180-15af-11e9-94be-76b4a95f7053.png">

没有速度。但是有进度 （一直是0kb/s,但是一直在下载 大小有变化）

**Comment by ZL335408** [comment]
下载的是最近版本加了下载进度的，在其它地方新建下载任务然后到下载任务列表中没有下载速度返回，点击暂停再开始后才会走下载速度的代理。

**Comment by XiaoYiS** [comment]
@onezens  你最新的代码在master上面，能否抽空打个tag呢
