### ISSUE TITLE
怎么计算下载速度啊

### ISSUE THREAD

**Issue by hupfei** [onezens/YCDownloadSession#8]

**Comment by shixiaoda** [comment]
https://github.com/ml-works/NetworkSpeedTest
may be help you

**Comment by onezens** [comment]
你是需要多个任务的总速度？

**Comment by hupfei** [comment]
单个任务各自的速度

**Comment by onezens** [comment]
单个任务到进度回调计算：
https://github.com/onezens/YCDownloadSession/blob/9e0daada4e81f357130bd1f75f4dcde433d55aa9/YCDownloadSession/YCDownloadSession/YCDownloadTask.h#L37

**Comment by hupfei** [comment]
我指的是  kb/s之类的

**Comment by onezens** [comment]
demo 视频列表第三个视频开启了下载速度的计算
注意切换到dev分支clone代码

https://github.com/onezens/YCDownloadSession/blob/e9754476cb99b7c9fe1a519aea1c7c290dfcb9f7/YCDownloadSession/YCDownloadSession/YCDownloadItem.h#L25
