### ISSUE TITLE
fileSize Error, task fileSize: 527675 tmp fileSize: 865448

### ISSUE THREAD

**Issue by PengKezhu** [onezens/YCDownloadSession#80]
手机型号：iPhone6
系统：iOS 12.1.2
操作步骤：下载过程中，kill掉app，再次打开后恢复下载，某些文件会出现这个问题，并且出现这些问题的文件会一直失败

**Comment by onezens** [comment]
kill掉app, 恢复下载，无法保证完全正常进行

**Comment by PengKezhu** [comment]
> kill掉app, 恢复下载，无法保证完全正常进行

我刚调试了下，发现tmp fileSize是对的，task fileSize有偏差，暂时不知道什么原因造成的

**Comment by onezens** [comment]
可以调试下，YCDownloadTask的downloadURL和NSURLSessionDownloadTask *downloadTask的request的url，看看是不是相同？

如果相同，那么就是kill app的时候，save数据出现了异常，
不同的话，kill app后，恢复数据的时候出现了异常

**Comment by onezens** [comment]
还有，你下载库是不是最新的，我这边测试了下，无法复现这个问题

**Comment by PengKezhu** [comment]
> 还有，你下载库是不是最新的，我这边测试了下，无法复现这个问题

- YCDownloadSession (2.0.2)
是最新的，我再调试下吧，每次刚好只有两个文件有这个问题

**Comment by lifuli** [comment]
我这边也出现了一样的问题

**Comment by PengKezhu** [comment]
> 我这边也出现了一样的问题
我暂时把判断条件(fileSize>0 && fileSize != task.fileSize)改成(fileSize>0 && fileSize<task.fileSize)了

**Comment by lifuli** [comment]
> fileSize>0 && fileSize<task.fileSize
好的 我试试
