### ISSUE TITLE
kDownloadTaskFinishedNoti通知时数据状态没更新

### ISSUE THREAD

**Issue by PengKezhu** [onezens/YCDownloadSession#81]
`        [[NSNotificationCenter defaultCenter] postNotificationName:kDownloadTaskFinishedNoti object:self];
`
`[YCDownloadDB saveItem:self];`
收到通知时，item对应的数据库状态没更新，我觉得应该把这两行代码交换下位置

**Comment by onezens** [comment]
https://github.com/onezens/YCDownloadSession/commit/f241918e4b4bc95c22d9fd8e6f920d9d8c114aac#diff-0add912d23a598303d08d91abaab1dbfL76
