### ISSUE TITLE
退出登录，登录新的账户，无法重新设置uid

### ISSUE THREAD

**Issue by StruggleXL** [onezens/YCDownloadSession#82]
你好，我看到YCDownloadManager只有在初始化单例时才会设置uid，当用户状态改变时，不能重新设置uid，希望提供api，感谢🙏

**Comment by onezens** [comment]
https://github.com/onezens/YCDownloadSession/blob/f241918e4b4bc95c22d9fd8e6f920d9d8c114aac/YCDownloadSession/YCDownloadManager.h#L55
