### ISSUE TITLE
下载超大视频异常

### ISSUE THREAD

**Issue by xjf1990930** [onezens/YCDownloadSession#85]
你好，我利用这个库用于下载视频管理，但是过程中发现DB中存储的一个10GB视频文件的文件大小为：72057593949421865，该数值转换为基本数据类型时却变成了负数，目测是超出longlong的可表示的最大数，并且10GB的视频数据并非存为几万兆的值，建议这个存储或者取出的方式可以优化一下数据类型，谢谢，叨扰了！
<img width="326" alt="QQ20190312-092348@2x" src="https://user-images.githubusercontent.com/12904118/54168357-0543c500-44a9-11e9-9c7e-5c8554b93603.png">
<img width="385" alt="QQ20190312-092517@2x" src="https://user-images.githubusercontent.com/12904118/54168359-0aa10f80-44a9-11e9-95a3-59a30f56d992.png">

**Comment by xjf1990930** [comment]
<img width="351" alt="QQ20190312-104733@2x" src="https://user-images.githubusercontent.com/12904118/54171151-5dcc8f80-44b4-11e9-8b79-9811218fe133.png">

**Comment by xjf1990930** [comment]
你好，经过调试，找到原因了，其实就是在超大文件下载完毕后将文件大小的数值存入数据库后出现了问题（本来要存入的值是11182816304，存入后变成了72057593949421865，导致拿出后错误），由于我对数据库这一块知识薄弱，无法做修正，所以还麻烦尽快修复这个问题，谢谢！

**Comment by onezens** [comment]
https://github.com/onezens/YCDownloadSession/commit/9b4565c8e7b1f3c9582ded2fe316dc27b2a7edd7
