### ISSUE TITLE
发现个数据库save的逻辑问题

### ISSUE THREAD

**Issue by allanGoldZhiKang** [onezens/YCDownloadSession#88]
如果内存缓存过的某个对象，但是在使用的过程中又对这个对象重新更新数据库了，但是再取这个对象的时候是从内存中读取的，而不是数据库中最新的数据。

**Comment by sensencoder** [comment]
saveDownloadTask 这个数据库存储逻辑有问题吧_memCacheTasks[task.taskId] = task;直接闪退了

**Comment by onezens** [comment]
请提供奔溃日志
