### ISSUE TITLE
切换网络 进度条不走

### ISSUE THREAD

**Issue by maoyuhu** [onezens/YCDownloadSession#93]
大佬, 切换网络之后  进度条不走 下载的大小也不动, 需要点击一下暂停 然后再开始 然后才继续下载  怎么解决呢

**Comment by maoyuhu** [comment]
大佬  你在哪

**Comment by pstkqzy** [comment]
切换网络 TCp连接就断了，需要手动启用继续下载，你可以在网络切换的时候做操作，继续下载

**Comment by onezens** [comment]
系统在切换网络后，会出现卡住得情况，目前没有解决办法
可手动或者代码重复调用刷新解决
